service: backend
runtime: nodejs20 # Specify the runtime

env: standard # Use the standard environment

instance_class: F1 # Choose an instance class (optional, based on your needs)

automatic_scaling:
  target_cpu_utilization: 0.6
  min_instances: 1
  max_instances: 5

handlers:
  - url: /* # Assuming your API endpoints start with /api/
    script: auto
    secure: always

  # Redirect all non-API requests to index.html
  # This might be needed if you're serving some static files directly from your backend or using it for other purposes alongside the API.
  - url: /(.*\.(gif|png|jpg|css|js))$
    static_files: build/\1
    upload: build/(.*\.(gif|png|jpg|css|js))$
    secure: always

  - url: /.*
    script: auto
    secure: always

network:
  session_affinity: true